# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7eaf6f20d331dbfd7d7cfae09d2a2719eebbf20d3a64a08bb39bd9411b75d8c23fb85807d55fe6aa523a5b698225f0630cce566df4dcb1005d9104e6759d745

test:
  secret_key_base: bd043f43070c93ebc287e0ae79790e0a5b6198d0a90dd0f98c761660114edd1b026a123c135c2630e9ab917aa7f7d3799b2164abed9e88fa37cb6f811a0ba83f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
